# Generated by Django 4.1.2 on 2024-06-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='camisetas',
            new_name='Camiseta',
        ),
    ]
