# Generated by Django 4.1.2 on 2024-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=50)),
            ],
        ),
    ]
