# Generated by Django 4.1.2 on 2024-06-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
    ]
